# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d70f1dcbf65b6490f7691a64be2a43be46668e05fc3ce4a1361cffab27e1cf483449c970ea5a9dfd35b44d5a12023f6f992e4090159b9811e2641b55a073753

test:
  secret_key_base: 19df5c558670f5c219e36a3be83f42537dd1a7006371c1046165bb8bfa43f8d6e1802999f4a594a671faca8f2bb49340458a87ccf5f6706b0ea998cbb975a2ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
